apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackeye-namespaces
  namespace: argocd
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: stackeye
  source:
    repoURL: https://github.com/StackEye-IO/stackeye-gitops
    targetRevision: main
    path: infrastructure/cnpg/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
