# Tailscale Auth Key Secret Template
# Required for worker pods to join the Tailscale network via sidecar container.
#
# IMPORTANT: This secret must be created on BOTH NYC3 and SFO3 clusters
# before worker pods can connect to the database via Tailscale.
#
# Prerequisites:
# 1. Generate an auth key at https://login.tailscale.com/admin/settings/keys
#    - Enable "Reusable" for multiple pod replicas
#    - Enable "Ephemeral" so devices auto-expire when pods terminate
#    - Tag with "tag:stackeye-worker" for ACL matching
# 2. Set expiration to max allowed (90 days) and rotate before expiry
#
# To create the secret:
#   1. Replace <TAILSCALE_AUTH_KEY> with your key from Tailscale admin
#   2. Apply to both clusters:
#      KUBECONFIG=~/.kube/mattox/stackeye-nyc3 kubectl apply -f secrets-template.yaml
#      KUBECONFIG=~/.kube/mattox/stackeye-sfo3 kubectl apply -f secrets-template.yaml
#
# Or use SealedSecrets for GitOps:
#   kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
#     --format=yaml < secrets-template.yaml > sealed-tailscale-auth.yaml

---
# Production namespace
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: stackeye-prd
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: tailscale-sidecar
    environment: prd
type: Opaque
stringData:
  # Tailscale auth key with tag:stackeye-worker
  # Generate at: https://login.tailscale.com/admin/settings/keys
  # Settings: Reusable=yes, Ephemeral=yes, Tags=tag:stackeye-worker
  authkey: "<TAILSCALE_AUTH_KEY>"

---
# Dev namespace
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: stackeye-dev
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: tailscale-sidecar
    environment: dev
type: Opaque
stringData:
  authkey: "<TAILSCALE_AUTH_KEY>"

---
# Staging namespace
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: stackeye-stg
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: tailscale-sidecar
    environment: stg
type: Opaque
stringData:
  authkey: "<TAILSCALE_AUTH_KEY>"
