apiVersion: v1
kind: Service
metadata:
  name: stackeye-valkey-lb
  namespace: stackeye-prd
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: cache
    environment: prd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: stackeye-valkey
    app.kubernetes.io/name: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP
