---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stackeye-web-secrets
  namespace: stackeye-stg
spec:
  encryptedData:
    AUTH0_CLIENT_SECRET: AgCOqbmxsd6rXDY7b0meToYdAFWBvwGfIIQEkTRdaTLa1/syIGDdZOsyMMMZ7SFRg55cuJsC2VW+XWq76DIwq14z/tX11+3pE2WbIfTQs//KyOuyI2qZcljvb4QpaSCWcbCi3bsvAirbezqRLwhJNXvcVA+Me7wwFbXkU+xa1a/ofvTd+5jK52e2Cg2nS2sfo+kF541NRYbdTpxD303qUQmQFlEdhZbimzuyeUS9ZZoAc4JuKchptcII2UMwdIZ+/I0blQ9mtiY/uRawdwIV7ls6LQ9JYOZcSDuUSVX4krX18Stia+kLwDxmOai09ckqGhRyl+96tVkLVyudER2h/cqPT6cVf1vUgvO1PblSUERnfWDz6EZSBtxRZjXNRsNlEvhQBXLRTNlGzweHVKtOGPooAvFeAk+jcfApsiMzFzxdoHhzVCc43GlUCafKkW3ioTZohTw0F+gZJHz/jmZ0n74i98p0SXpjNkzZxMTKQkzL9olScOMH9XIIUUoPQaRFakFrkn2sEFjdQnlpboBjcf9h3P3Cyo9FT8V81CIWpUbP9FRoZj8mugN28ZbAe6WE22xSiIIcfDEfpdWWPsql0hlj5PoYJzISY8scHBptMMQRSPzrmepST4YZtar7ksxeXzw5YujoQ5+xA7/QmLk4rWq/OpBh5+rUfhkQ+iGpRPVpUF3iaZcvA6wS23B+EVrb6lnq/+748DZqqxxDdbBU5EthVc0AbeUaoQCaDqGmA7BLNbw=
    AUTH0_SECRET: AgBRQLquhP1kybNliNJIPSLc5o79sPme6R0zsFF+IHLlWtTSPUkTKRf767049ToOXocW0cXpmb/XEF6/P0Zt0zASijzGL++nxoIGZe2ToUFzAL3qyqUNWvX8i1wLAgyIc0BRfyNcyWV4A6NMHb4m/Hd8KAwPbwIayVBG7pcWwTvuDxA0nEhYZ0oRksMTuIWXfZSz80DNcxd5F0giaNSRA0gRnCFxKujFCRZ9LSRCWrWc0xyT9VmIfTER54ndw+ci5MQAovtO3D8q+sh5YLSn/WOv+UfIqUAbK0DQjQvM1ZBljq1aGMb+L7Kq4YXdAWokf8ejVxRaAyRJigRnaTrZj28hxYjxNemuaTQ//a1XvE41vIkFF3+i+Jzsk98lhEAJztSgQ79u/V2ZN5WQwMS6ogdVO0oy12+Tux61J365OYS1zN7FnFtzTj43h88BRI6yQ+bQDCak13bsadCMB8v6zYaJc5zH8YTyE+NLi9/b45v+bxAKJv0/KVS61TOdWix0TbteR1J/J7DNKnbuqxauY1G5qsF9+oFwQ+SBGiYpiH6+5ZAX1G0KdJQ0uY0uZYcG0uGcYjuIjaaHTjYuGo2aHMNAUAG5D63hDxX9u6ykFJlnjGjVyCgZV8YUxif75Ky/wPPaWh+Ra9mXVVUQeSMAyJMqOFEEMlVrQB/76Cg1sgs3vXxYgAFJ1Frp89j9QfcufnhQdwNgnLFt3iYn+ZtTfWlzgae62XfTDSn/tIi09lZEMBIf1ZbhrvThfo0SjGMStZTVTTiYNxvOJNS+xUbAUi3r
  template:
    metadata:
      creationTimestamp: null
      name: stackeye-web-secrets
      namespace: stackeye-stg
    type: Opaque
