# Template for creating backup credentials
# This secret needs to be created in each namespace before deploying the clusters.
# The values should match the existing Wasabi S3 credentials used for PostgreSQL backups.
#
# Option 1: Create the secret manually in each namespace
# Option 2: Use SealedSecrets to encrypt and store in git
#
# Note: The harbor-supporttools secret is automatically provisioned by kubetty.

---
# Template - DO NOT APPLY DIRECTLY
# Replace <BASE64_ACCESS_KEY> and <BASE64_SECRET_KEY> with actual values
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-credentials
  # Apply to each namespace: stackeye-dev, stackeye-stg, stackeye-prd
type: Opaque
data:
  ACCESS_KEY_ID: <BASE64_ACCESS_KEY>
  SECRET_ACCESS_KEY: <BASE64_SECRET_KEY>

---
# To create the secret, run:
# for ns in stackeye-dev stackeye-stg stackeye-prd; do
#   kubectl create secret generic postgres-backup-credentials \
#     --from-literal=ACCESS_KEY_ID="your-access-key" \
#     --from-literal=SECRET_ACCESS_KEY="your-secret-key" \
#     -n $ns
# done
