apiVersion: v1
kind: Service
metadata:
  name: stackeye-db-rw-lb
  namespace: stackeye-dev
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: database
    environment: dev
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: stackeye-db
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
