# Template for creating worker database connection secrets
# These secrets need to be created in the worker namespaces on NYC3 and SFO3 clusters.
#
# PREREQUISITE: Tailscale Connectors must be deployed on NYC3/SFO3 before workers
# can connect to these Tailscale hostnames. See docs/tailscale-connectivity.md
#
# Option 1: Create the secrets manually in each namespace
# Option 2: Use SealedSecrets to encrypt and store in git (recommended)
#
# Note: See .claude/secrets/stackeye-db-connections.env for actual credentials

---
# DEV Environment Worker Secret Template
# Deploy to: stackeye-nyc3 and stackeye-sfo3 clusters
apiVersion: v1
kind: Secret
metadata:
  name: stackeye-worker-db
  namespace: stackeye-dev
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: worker
    environment: dev
type: Opaque
stringData:
  # PostgreSQL via Tailscale (requires Connector on worker cluster)
  DATABASE_URL: "postgres://stackeye:<password>@stackeye-db-dev:5432/stackeye?sslmode=require"

  # Valkey (Redis) via Tailscale
  REDIS_URL: "redis://:<password>@stackeye-valkey-dev:6379/0"

  # Individual components (for apps that need them separately)
  DB_HOST: "stackeye-db-dev"
  DB_PORT: "5432"
  DB_NAME: "stackeye"
  DB_USER: "stackeye"
  DB_PASSWORD: "<password>"
  DB_SSLMODE: "require"

  REDIS_HOST: "stackeye-valkey-dev"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "<password>"

---
# STG Environment Worker Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: stackeye-worker-db
  namespace: stackeye-stg
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: worker
    environment: stg
type: Opaque
stringData:
  DATABASE_URL: "postgres://stackeye:<password>@stackeye-db-stg:5432/stackeye?sslmode=require"
  REDIS_URL: "redis://:<password>@stackeye-valkey-stg:6379/0"
  DB_HOST: "stackeye-db-stg"
  DB_PORT: "5432"
  DB_NAME: "stackeye"
  DB_USER: "stackeye"
  DB_PASSWORD: "<password>"
  DB_SSLMODE: "require"
  REDIS_HOST: "stackeye-valkey-stg"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "<password>"

---
# PRD Environment Worker Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: stackeye-worker-db
  namespace: stackeye-prd
  labels:
    app.kubernetes.io/name: stackeye
    app.kubernetes.io/component: worker
    environment: prd
type: Opaque
stringData:
  DATABASE_URL: "postgres://stackeye:<password>@stackeye-db-prd:5432/stackeye?sslmode=require"
  REDIS_URL: "redis://:<password>@stackeye-valkey-prd:6379/0"
  DB_HOST: "stackeye-db-prd"
  DB_PORT: "5432"
  DB_NAME: "stackeye"
  DB_USER: "stackeye"
  DB_PASSWORD: "<password>"
  DB_SSLMODE: "require"
  REDIS_HOST: "stackeye-valkey-prd"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "<password>"

---
# To create the secrets using SealedSecrets:
#
# 1. First, ensure Tailscale Connectors are deployed on NYC3/SFO3
#    (see docs/tailscale-connectivity.md for Connector manifests)
#
# 2. Replace <password> values with actual credentials from:
#    .claude/secrets/stackeye-db-connections.env
#
# 3. Seal the secrets:
#    kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
#      --format=yaml < worker-secrets-dev.yaml > sealed-worker-secrets-dev.yaml
#
# 4. Apply to NYC3 and SFO3 clusters:
#    kubectl apply -f sealed-worker-secrets-dev.yaml --context=stackeye-nyc3
#    kubectl apply -f sealed-worker-secrets-dev.yaml --context=stackeye-sfo3
